
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'left+-left*/left^rightUMINUSINT FLOAT PRINT BOOLEAN TRUE FALSE NAME INUM FNUMinit : statementstatement : declarations ";" statement\n                 | print ";" statement\n                 | emptyempty :type : INT\n            | FLOAT\n            | BOOLEANdeclarations  : declaration_type_name\n                     | declaration_assign_expression\n                     | declaration_fulldeclaration_type_name : type NAMEdeclaration_assign_expression : NAME "=" expressiondeclaration_full : type NAME "=" expressionprint : PRINT expressionexpression : expression "+" expression\n                  | expression "-" expression\n                  | expression "*" expression\n                  | expression "/" expression\n                  | expression "^" expressionexpression : "-" expression %prec UMINUSexpression : "(" expression ")"expression : INUM\n                  | FNUM\n                  | BOOLVALexpression : NAMEBOOLVAL : TRUE\n               | FALSE'
    
_lr_action_items = {'PRINT':([0,15,16,],[9,9,9,]),'$end':([0,1,2,5,15,16,28,29,],[-5,0,-1,-4,-5,-5,-2,-3,]),'NAME':([0,9,10,12,13,14,15,16,18,19,27,30,31,32,33,34,37,],[11,23,26,-6,-7,-8,11,11,23,23,23,23,23,23,23,23,23,]),'INT':([0,15,16,],[12,12,12,]),'FLOAT':([0,15,16,],[13,13,13,]),'BOOLEAN':([0,15,16,],[14,14,14,]),';':([3,4,6,7,8,17,20,21,22,23,24,25,26,35,38,39,40,41,42,43,44,45,],[15,16,-9,-10,-11,-15,-23,-24,-25,-26,-27,-28,-12,-21,-13,-16,-17,-18,-19,-20,-22,-14,]),'-':([9,17,18,19,20,21,22,23,24,25,27,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,],[18,31,18,18,-23,-24,-25,-26,-27,-28,18,18,18,18,18,18,-21,31,18,31,-16,-17,-18,-19,-20,-22,31,]),'(':([9,18,19,27,30,31,32,33,34,37,],[19,19,19,19,19,19,19,19,19,19,]),'INUM':([9,18,19,27,30,31,32,33,34,37,],[20,20,20,20,20,20,20,20,20,20,]),'FNUM':([9,18,19,27,30,31,32,33,34,37,],[21,21,21,21,21,21,21,21,21,21,]),'TRUE':([9,18,19,27,30,31,32,33,34,37,],[24,24,24,24,24,24,24,24,24,24,]),'FALSE':([9,18,19,27,30,31,32,33,34,37,],[25,25,25,25,25,25,25,25,25,25,]),'=':([11,26,],[27,37,]),'+':([17,20,21,22,23,24,25,35,36,38,39,40,41,42,43,44,45,],[30,-23,-24,-25,-26,-27,-28,-21,30,30,-16,-17,-18,-19,-20,-22,30,]),'*':([17,20,21,22,23,24,25,35,36,38,39,40,41,42,43,44,45,],[32,-23,-24,-25,-26,-27,-28,-21,32,32,32,32,-18,-19,-20,-22,32,]),'/':([17,20,21,22,23,24,25,35,36,38,39,40,41,42,43,44,45,],[33,-23,-24,-25,-26,-27,-28,-21,33,33,33,33,-18,-19,-20,-22,33,]),'^':([17,20,21,22,23,24,25,35,36,38,39,40,41,42,43,44,45,],[34,-23,-24,-25,-26,-27,-28,-21,34,34,34,34,34,34,-20,-22,34,]),')':([20,21,22,23,24,25,35,36,39,40,41,42,43,44,],[-23,-24,-25,-26,-27,-28,-21,44,-16,-17,-18,-19,-20,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'statement':([0,15,16,],[2,28,29,]),'declarations':([0,15,16,],[3,3,3,]),'print':([0,15,16,],[4,4,4,]),'empty':([0,15,16,],[5,5,5,]),'declaration_type_name':([0,15,16,],[6,6,6,]),'declaration_assign_expression':([0,15,16,],[7,7,7,]),'declaration_full':([0,15,16,],[8,8,8,]),'type':([0,15,16,],[10,10,10,]),'expression':([9,18,19,27,30,31,32,33,34,37,],[17,35,36,38,39,40,41,42,43,45,]),'BOOLVAL':([9,18,19,27,30,31,32,33,34,37,],[22,22,22,22,22,22,22,22,22,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> statement','init',1,'p_init','ly_calc.py',58),
  ('statement -> declarations ; statement','statement',3,'p_statement','ly_calc.py',64),
  ('statement -> print ; statement','statement',3,'p_statement','ly_calc.py',65),
  ('statement -> empty','statement',1,'p_statement','ly_calc.py',66),
  ('empty -> <empty>','empty',0,'p_empty','ly_calc.py',74),
  ('type -> INT','type',1,'p_type_specifier','ly_calc.py',78),
  ('type -> FLOAT','type',1,'p_type_specifier','ly_calc.py',79),
  ('type -> BOOLEAN','type',1,'p_type_specifier','ly_calc.py',80),
  ('declarations -> declaration_type_name','declarations',1,'p_declarations','ly_calc.py',85),
  ('declarations -> declaration_assign_expression','declarations',1,'p_declarations','ly_calc.py',86),
  ('declarations -> declaration_full','declarations',1,'p_declarations','ly_calc.py',87),
  ('declaration_type_name -> type NAME','declaration_type_name',2,'p_declaration_type_name','ly_calc.py',91),
  ('declaration_assign_expression -> NAME = expression','declaration_assign_expression',3,'p_declaration_assign_expression','ly_calc.py',96),
  ('declaration_full -> type NAME = expression','declaration_full',4,'p_declaration_full','ly_calc.py',100),
  ('print -> PRINT expression','print',2,'p_print','ly_calc.py',104),
  ('expression -> expression + expression','expression',3,'p_expression_binop','ly_calc.py',109),
  ('expression -> expression - expression','expression',3,'p_expression_binop','ly_calc.py',110),
  ('expression -> expression * expression','expression',3,'p_expression_binop','ly_calc.py',111),
  ('expression -> expression / expression','expression',3,'p_expression_binop','ly_calc.py',112),
  ('expression -> expression ^ expression','expression',3,'p_expression_binop','ly_calc.py',113),
  ('expression -> - expression','expression',2,'p_expression_uminus','ly_calc.py',117),
  ('expression -> ( expression )','expression',3,'p_direct_declarator','ly_calc.py',122),
  ('expression -> INUM','expression',1,'p_expression_number','ly_calc.py',127),
  ('expression -> FNUM','expression',1,'p_expression_number','ly_calc.py',128),
  ('expression -> BOOLVAL','expression',1,'p_expression_number','ly_calc.py',129),
  ('expression -> NAME','expression',1,'p_expression_name','ly_calc.py',133),
  ('BOOLVAL -> TRUE','BOOLVAL',1,'p_boolean','ly_calc.py',137),
  ('BOOLVAL -> FALSE','BOOLVAL',1,'p_boolean','ly_calc.py',138),
]
